part of 'approval_providers.dart';

const _frequentForms = [
  ApprovalForm(
    id: 'team-vacation',
    name: '팀 휴가 결재서',
    description: '팀 단위 휴가 일정 승인',
    recentCount: 12,
  ),
  ApprovalForm(
    id: 'expense-slip',
    name: '지출 결의서(지급품의)',
    description: '비용 지급 승인',
    recentCount: 9,
  ),
  ApprovalForm(
    id: 'business-draft',
    name: '업무기안[기본양식]',
    description: '일반 기안 문서',
    recentCount: 15,
  ),
];

const _templates = [
  ApprovalFormTemplate(
    id: 'business-draft',
    category: '지원',
    name: '업무기안[기본양식]',
    description: '일반 기안 작성',
    defaultTitle: '정산을 위한 운영인력 충원의 건',
    defaultContent:
        '신규 콘텐츠 마케팅 진행에 따라 원활한 정산을 위한 운영 인력 채용 또는 내부 인력 배정을 요청드립니다.\n\n1. 요청 인원: 1명\n2. 필요 업무: 실시간 업무지원, 회계 처리, 세금계산서 대응\n3. 요청 사유: 캠페인 집행 증가에 따른 운영 부담 완화',
    receivers: ['경영관리팀'],
    references: ['부서장'],
    viewers: ['운영지원 담당자'],
    publicReceivers: ['다우기술'],
    cooperationDepartment: '경영관리팀',
    agreement: '순차합의',
  ),
  ApprovalFormTemplate(
    id: 'expense-slip',
    category: '회계',
    name: '지출 결의서(지급품의)',
    description: '비용 지급 승인',
    defaultTitle: '교육장 기자재 대여 비용 집행 요청',
    defaultContent:
        '교육장 실습 장비 대여 비용 집행 승인을 요청드립니다.\n\n1. 대여 장비: 노트북 12대, 프로젝터 2대\n2. 사용 일정: 2026-07-03 ~ 2026-07-05\n3. 요청 금액: 2,850,000원',
    receivers: ['재경팀'],
    references: ['교육관리팀 부장'],
    viewers: ['교육 대상자'],
    publicReceivers: ['다우기술'],
    cooperationDepartment: '재경팀',
    agreement: '예산 확인 후 지급',
    documentLayout: ApprovalDocumentLayout.expense,
    lineItemRows: 32,
  ),
  ApprovalFormTemplate(
    id: 'purchase-request',
    category: '지원',
    name: '비품/소모품 구입신청서',
    description: '비품 및 소모품 구매 요청',
    defaultTitle: '업무용 PC 구매 예산 할당 요청',
    defaultContent:
        '업무용 PC 구매 예산 할당 요청 재가 바랍니다.\n\n1. 구매 목적: 노후 PC 교체 및 교육 실습 장비 확보\n2. 구매 품목: 데스크톱 PC 6대, 모니터 6대\n3. 예산 요청: 9,600,000원',
    receivers: ['재경팀'],
    references: ['교육관리팀 부장', '구매 담당자'],
    viewers: ['교육관리팀 구성원'],
    publicReceivers: ['다우기술'],
    cooperationDepartment: '재경팀',
    agreement: '합의 후 구매 진행',
    documentLayout: ApprovalDocumentLayout.purchase,
    lineItemRows: 16,
  ),
  ApprovalFormTemplate(
    id: 'hospitality-expense',
    category: '회계',
    name: '지출결의서(기업업무추진비)',
    description: '접대비 및 기업업무추진비 결재',
    defaultTitle: '기업업무추진비 집행 요청',
    defaultContent: '업무 관련 접대비 집행 내역을 아래와 같이 상신합니다.',
    receivers: ['재경팀'],
    references: ['경영관리팀'],
    viewers: ['회계 담당자'],
    publicReceivers: ['다우기술'],
    cooperationDepartment: '재경팀',
    agreement: '증빙 확인 후 지급',
    documentLayout: ApprovalDocumentLayout.hospitality,
    lineItemRows: 24,
  ),
  ApprovalFormTemplate(
    id: 'payroll-draft',
    category: '회계',
    name: '급여대장 기안서',
    description: '급여대장 인가 및 지급 기안',
    defaultTitle: '급여대장 지급 승인 요청',
    defaultContent: '급여대장 지급 승인을 요청드립니다.',
    receivers: ['경영관리팀'],
    references: ['인사 담당자'],
    viewers: ['급여 담당자'],
    publicReceivers: [],
    cooperationDepartment: '경영관리팀',
    agreement: '급여대장 확인',
    documentLayout: ApprovalDocumentLayout.payroll,
    lineItemRows: 1,
  ),
  ApprovalFormTemplate(
    id: 'team-vacation',
    category: '근태',
    name: '팀 휴가 결재서',
    description: '팀 휴가 일정 승인',
    defaultTitle: '7월 교육관리팀 팀 휴가 일정 승인',
    defaultContent:
        '교육관리팀 7월 휴가 일정을 아래와 같이 상신합니다.\n\n1. 휴가 기간: 2026-07-08 ~ 2026-07-12\n2. 대상자: 교육강사, 교육관리자, 운영지원 담당자\n3. 업무 인수인계: 이재오 차장이 교육 문의 1차 대응\n4. 요청사항: 팀 휴가 일정 승인 및 인사관리팀 공유',
    receivers: ['인사관리팀'],
    references: ['교육관리팀 부장', '운영지원 담당자'],
    viewers: ['교육관리팀 구성원'],
    publicReceivers: ['다우기술'],
    cooperationDepartment: '인사관리팀',
    agreement: '팀 운영 일정 확인',
  ),
  ApprovalFormTemplate(
    id: 'cooperation-request',
    category: '협조',
    name: '업무협조[기본양식]',
    description: '타 부서 협조 요청',
    defaultTitle: '신규 교육 과정 운영 협조 요청',
    defaultContent:
        '신규 교육 과정 운영을 위한 부서 협조를 요청드립니다.\n\n1. 운영 일정: 2026-07-15 ~ 2026-07-30\n2. 협조 요청 부서: 운영팀, 재경팀\n3. 요청사항: 일정 공유 및 예산 집행 검토',
    receivers: ['운영팀'],
    references: ['교육관리팀 부장'],
    viewers: ['경영지원팀'],
    publicReceivers: ['다우기술'],
    cooperationDepartment: '운영팀',
    agreement: '협조 승인',
  ),
];

const _accounts = [
  EmployeeAccount(
    id: 'edu_teacher',
    password: '1234',
    name: '교육강사',
    department: '교육관리팀',
    position: '대리',
    email: 'edu_teacher@thewe.co.kr',
  ),
  EmployeeAccount(
    id: 'edu_manager',
    password: '1234',
    name: '교육관리자',
    department: '교육관리팀',
    position: '과장',
    email: 'edu_manager@thewe.co.kr',
    isAdmin: true,
  ),
  EmployeeAccount(
    id: 'lee_jaeo',
    password: '1234',
    name: '이재오',
    department: '교육관리팀',
    position: '차장',
    email: 'lee_jaeo@thewe.co.kr',
  ),
  EmployeeAccount(
    id: 'kim_kyunyoung',
    password: '1234',
    name: '김경영',
    department: '경영관리팀',
    position: '상무',
    email: 'kim_kyunyoung@thewe.co.kr',
  ),
  EmployeeAccount(
    id: 'jiyun',
    password: '1234',
    name: '정지윤',
    department: '마케팅팀',
    position: '대리',
    email: 'jiyun@thewe.co.kr',
  ),
  EmployeeAccount(
    id: 'han_dev',
    password: '1234',
    name: '한유진',
    department: '개발팀',
    position: '과장',
    email: 'han_dev@thewe.co.kr',
  ),
  EmployeeAccount(
    id: 'director',
    password: '1234',
    name: '정효정',
    department: '경영관리팀',
    position: '이사',
    email: 'director@thewe.co.kr',
  ),
  EmployeeAccount(
    id: 'ceo',
    password: '1234',
    name: '조상훈',
    department: '경영관리팀',
    position: '대표',
    email: 'ceo@thewe.co.kr',
  ),
];
