part of 'approval_providers.dart';

final _seedDocuments = [
  ApprovalDocument(
    id: 'APR-260629-001',
    title: '업무용 PC 구매 예산 할당 요청',
    drafter: '교육강사',
    department: '교육관리팀',
    form: '구매 요청서',
    status: '결재대기',
    draftedAt: '2026-06-29',
    dueDate: '2026-07-02',
    progress: 33,
    documentNo: 'APR-260629-001',
    effectiveDate: '2026-07-02',
    cooperationDepartment: '재경팀',
    agreement: '합의 후 구매 진행',
    content:
        '업무용 PC 구매 예산 할당 요청 재가 바랍니다.\n\n1. 구매 목적: 노후 PC 교체 및 교육 실습 장비 확보\n2. 구매 품목: 데스크톱 PC 6대, 모니터 6대\n3. 예산 요청: 9,600,000원',
    urgent: true,
    receivedRequest: true,
    canCancel: true,
    receivers: ['재경팀'],
    references: ['교육관리팀 부장', '구매 담당자'],
    viewers: ['교육관리팀 구성원'],
    publicReceivers: ['다우기술'],
    linkedDocuments: ['구매 사양서.pdf'],
    steps: [
      ApprovalStep(
        name: '교육강사',
        department: '교육관리팀',
        type: '신청',
        role: '대리',
        status: '완료',
        approvedAt: '2026-06-29 09:20',
      ),
      ApprovalStep(
        name: '이재오',
        department: '교육관리팀',
        type: '승인',
        role: '차장',
        status: '진행중',
      ),
      ApprovalStep(
        name: '김경영',
        department: '경영관리팀',
        type: '승인',
        role: '상무',
        status: '결재 예정',
      ),
    ],
    histories: [
      ApprovalHistory(
        id: 'HIS-260629-001',
        category: '결재문서 변경',
        date: '2026-06-29 09:20',
        user: '교육강사 대리',
        description: '결재 요청 상신',
        snapshot: '업무용 PC 구매 예산 할당 요청',
      ),
    ],
  ),
  ApprovalDocument(
    id: 'APR-260628-002',
    title: '지출결의서(지급품의) 6월 교육 기자재 대여비',
    drafter: '교육관리자',
    department: '교육관리팀',
    form: '지출 결의서(지급품의)',
    status: '결재대기',
    draftedAt: '2026-06-28',
    dueDate: '2026-07-01',
    progress: 67,
    documentNo: 'APR-260628-002',
    effectiveDate: '2026-07-01',
    cooperationDepartment: '재경팀',
    agreement: '예산 확인 후 지급',
    content:
        '교육 기자재 대여 비용에 대한 지급 승인을 요청드립니다.\n\n1. 대여처: 위드렌탈\n2. 사용 장비: 노트북 12대, 프로젝터 2대\n3. 지급 요청 금액: 2,850,000원',
    receivedRequest: true,
    canCancel: false,
    receivers: ['재경팀'],
    references: ['교육관리팀 부장'],
    viewers: ['교육 대상자'],
    publicReceivers: ['다우기술'],
    linkedDocuments: ['견적서.pdf', '계약서.pdf'],
    steps: [
      ApprovalStep(
        name: '교육관리자',
        department: '교육관리팀',
        type: '신청',
        role: '과장',
        status: '완료',
        approvedAt: '2026-06-28 13:00',
      ),
      ApprovalStep(
        name: '이재오',
        department: '교육관리팀',
        type: '승인',
        role: '차장',
        status: '완료',
        approvedAt: '2026-06-29 08:30',
      ),
      ApprovalStep(
        name: '김경영',
        department: '경영관리팀',
        type: '승인',
        role: '상무',
        status: '진행중',
      ),
    ],
    histories: [
      ApprovalHistory(
        id: 'HIS-260628-002',
        category: '결재문서 변경',
        date: '2026-06-29 08:30',
        user: '이재오 차장',
        description: '1차 승인 완료',
        snapshot: '지출결의서(지급품의) 6월 교육 기자재 대여비',
      ),
    ],
  ),
  ApprovalDocument(
    id: 'APR-260627-003',
    title: '6월 마케팅 캠페인 예산 승인',
    drafter: '정지윤',
    department: '마케팅팀',
    form: '지출 결의서(지급품의)',
    status: '완료',
    draftedAt: '2026-06-27',
    dueDate: '2026-06-29',
    progress: 100,
    documentNo: 'APR-260627-003',
    effectiveDate: '2026-06-29',
    cooperationDepartment: '재무팀',
    agreement: '예산 범위 내 집행',
    content: '6월 마케팅 캠페인 진행에 필요한 광고비와 운영비 집행 승인을 요청드립니다.',
    receivedRequest: true,
    canCancel: false,
    receivers: ['재무팀'],
    references: ['마케팅팀장'],
    viewers: ['교육관리자'],
    publicReceivers: ['다우기술'],
    linkedDocuments: ['캠페인 운영안.pdf'],
    steps: [
      ApprovalStep(
        name: '정지윤',
        department: '마케팅팀',
        type: '신청',
        role: '대리',
        status: '완료',
        approvedAt: '2026-06-27 10:00',
      ),
      ApprovalStep(
        name: '김경영',
        department: '경영관리팀',
        type: '승인',
        role: '상무',
        status: '완료',
        approvedAt: '2026-06-28 09:10',
      ),
    ],
    histories: [
      ApprovalHistory(
        id: 'HIS-260627-003',
        category: '결재문서 변경',
        date: '2026-06-28 09:10',
        user: '김경영 상무',
        description: '최종 승인 완료',
        snapshot: '6월 마케팅 캠페인 예산 승인',
      ),
    ],
  ),
  ApprovalDocument(
    id: 'APR-260630-004',
    title: '운영지원 소모품 구매 승인 요청',
    drafter: '한유진',
    department: '개발팀',
    form: '구매 요청서',
    status: '결재대기',
    draftedAt: '2026-06-30',
    dueDate: '2026-07-03',
    progress: 50,
    documentNo: 'APR-260630-004',
    effectiveDate: '2026-07-03',
    cooperationDepartment: '경영관리팀',
    agreement: '구매 검토 후 진행',
    content:
        '운영지원에 필요한 소모품 구매 승인을 요청드립니다.\n\n1. 구매 품목: 회의실 소모품 및 케이블류\n2. 사용 부서: 개발팀, 교육관리팀\n3. 요청 금액: 680,000원',
    receivedRequest: true,
    canCancel: false,
    receivers: ['교육관리팀'],
    references: ['교육관리자'],
    viewers: ['교육강사'],
    publicReceivers: ['다우기술'],
    linkedDocuments: ['소모품 견적서.pdf'],
    steps: [
      ApprovalStep(
        name: '한유진',
        department: '개발팀',
        type: '신청',
        role: '과장',
        status: '완료',
        approvedAt: '2026-06-30 09:30',
      ),
      ApprovalStep(
        name: '교육강사',
        department: '교육관리팀',
        type: '승인',
        role: '대리',
        status: '진행중',
      ),
      ApprovalStep(
        name: '김경영',
        department: '경영관리팀',
        type: '승인',
        role: '상무',
        status: '결재 예정',
      ),
    ],
    histories: [
      ApprovalHistory(
        id: 'HIS-260630-004',
        category: '결재문서 변경',
        date: '2026-06-30 09:30',
        user: '한유진 과장',
        description: '결재 요청 상신',
        snapshot: '운영지원 소모품 구매 승인 요청',
      ),
    ],
  ),
  ApprovalDocument(
    id: 'APR-260630-005',
    title: '교육관리팀 외부 세미나 참석 계획',
    drafter: '이재오',
    department: '교육관리팀',
    form: '업무기안[기본양식]',
    status: '결재대기',
    draftedAt: '2026-06-30',
    dueDate: '2026-07-04',
    progress: 50,
    documentNo: 'APR-260630-005',
    effectiveDate: '2026-07-04',
    cooperationDepartment: '교육관리팀',
    agreement: '부서 일정 확인',
    content:
        '교육관리팀 외부 세미나 참석 계획을 공유하고 결재를 요청드립니다.\n\n1. 참석 일정: 2026-07-10\n2. 참석자: 교육강사, 교육관리자\n3. 목적: 신규 교육 과정 벤치마킹',
    receivedRequest: true,
    canCancel: false,
    receivers: ['경영관리팀'],
    references: ['교육강사'],
    viewers: ['교육관리자'],
    publicReceivers: ['다우기술'],
    linkedDocuments: ['세미나 안내문.pdf'],
    steps: [
      ApprovalStep(
        name: '이재오',
        department: '교육관리팀',
        type: '신청',
        role: '차장',
        status: '완료',
        approvedAt: '2026-06-30 10:10',
      ),
      ApprovalStep(
        name: '김경영',
        department: '경영관리팀',
        type: '승인',
        role: '상무',
        status: '진행중',
      ),
      ApprovalStep(
        name: '교육강사',
        department: '교육관리팀',
        type: '열람',
        role: '대리',
        status: '결재 예정',
      ),
    ],
    histories: [
      ApprovalHistory(
        id: 'HIS-260630-005',
        category: '결재문서 변경',
        date: '2026-06-30 10:10',
        user: '이재오 차장',
        description: '결재 요청 상신',
        snapshot: '교육관리팀 외부 세미나 참석 계획',
      ),
    ],
  ),
  ApprovalDocument(
    id: 'DRF-260629-001',
    title: '하반기 교육 커리큘럼 개편안',
    drafter: '교육강사',
    department: '교육관리팀',
    form: '업무기안[기본양식]',
    status: '작성중',
    draftedAt: '2026-06-29',
    dueDate: '2026-06-29',
    progress: 0,
    documentNo: '임시저장',
    effectiveDate: '2026-06-29',
    cooperationDepartment: '교육관리팀',
    agreement: '검토 후 진행',
    content:
        '하반기 교육 커리큘럼 개편안 초안을 작성 중입니다.\n\n1. 신규 과정 3종 추가\n2. 실습 비중 확대\n3. 사전 설문 반영',
    canEdit: true,
    receivers: ['교육관리팀'],
    references: ['이재오'],
    viewers: ['교육관리자'],
    publicReceivers: ['다우기술'],
    linkedDocuments: [],
    steps: [
      ApprovalStep(
        name: '교육강사',
        department: '교육관리팀',
        type: '신청',
        role: '대리',
        status: '기안',
      ),
      ApprovalStep(
        name: '이재오',
        department: '교육관리팀',
        type: '승인',
        role: '차장',
        status: '결재 예정',
      ),
      ApprovalStep(
        name: '김경영',
        department: '경영관리팀',
        type: '승인',
        role: '상무',
        status: '결재 예정',
      ),
    ],
  ),
];
